export const STORAGE_PATH_SET = 'STORAGE_PATH_SET'

export const VAULTS_INIT = 'VAULTS_INIT'
export const VAULTS_GET_STATUS = 'VAULTS_GET_STATUS'
export const VAULTS_GET = 'VAULTS_GET'
export const VAULTS_CLOSE = 'VAULTS_CLOSE'
export const VAULTS_ADD = 'VAULTS_ADD'
export const VAULTS_LIST = 'VAULTS_LIST'

export const ACTIVE_VAULT_INIT = 'ACTIVE_VAULT_INIT'
export const ACTIVE_VAULT_GET_STATUS = 'ACTIVE_VAULT_GET_STATUS'
export const ACTIVE_VAULT_CLOSE = 'ACTIVE_VAULT_CLOSE'
export const ACTIVE_VAULT_ADD = 'ACTIVE_VAULT_ADD'
export const ACTIVE_VAULT_REMOVE = 'ACTIVE_VAULT_REMOVE'
export const ACTIVE_VAULT_LIST = 'ACTIVE_VAULT_LIST'
export const ACTIVE_VAULT_GET = 'ACTIVE_VAULT_GET'
export const ACTIVE_VAULT_CREATE_INVITE = 'ACTIVE_VAULT_CREATE_INVITE'
export const ACTIVE_VAULT_DELETE_INVITE = 'ACTIVE_VAULT_DELETE_INVITE'

export const PAIR = 'PAIR'
export const INIT_LISTENER = 'INIT_LISTENER'
export const ON_UPDATE = 'ON_UPDATE'

export const ENCRYPTION_INIT = 'ENCRYPTION_INIT'
export const ENCRYPTION_GET_STATUS = 'ENCRYPTION_GET_STATUS'
export const ENCRYPTION_GET = 'ENCRYPTION_GET'
export const ENCRYPTION_ADD = 'ENCRYPTION_ADD'
export const ENCRYPTION_CLOSE = 'ENCRYPTION_CLOSE'
export const ENCRYPTION_HASH_PASSWORD = 'ENCRYPTION_HASH_PASSWORD'
export const ENCRYPTION_ENCRYPT_VAULT_KEY_WITH_HASHED_PASSWORD =
  'ENCRYPTION_ENCRYPT_VAULT_KEY_WITH_HASHED_PASSWORD'
export const ENCRYPTION_ENCRYPT_VAULT_WITH_KEY =
  'ENCRYPTION_ENCRYPT_VAULT_WITH_KEY'
export const ENCRYPTION_DECRYPT_VAULT_KEY = 'ENCRYPTION_DECRYPT_VAULT_KEY'
export const ENCRYPTION_GET_DECRYPTION_KEY = 'ENCRYPTION_GET_DECRYPTION_KEY'

export const CLOSE = 'CLOSE'
